services:
  backend:
    build:
      context: .
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      LOG_LEVEL: info
      LOG_FORMAT: json
